NAMA        : REZA PUTRI ANGGA
NPM         : 22083010006
MATA KULIAH : ANALISIS DATA EKSPLORATIF (A)

# Visualisasi Data Interaktif

Implementasikan Dasbor Visualisasi Data Interaktif Untuk Memvisualisasikan Dataset Iris Dengan Beberapa Menu, Yakni :

a. Variabel X dan Y : Sepal Length, Sepal Width, Petal Length, Dan Petal
Width (Dropdown Button)

b. Jumlah Kelas     : 3 (Default)

Melakukan Proses Load (Pembacaan) Data Dari Dataset Iris Yang Akan Di Analisis Lebih Lanjut

In [1]:
import pandas as pd

DataIris = pd.read_csv("iris.csv")
DataIris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

Melakukan Proses Rename (Pengubahan) Nama-Nama Kolom Pada Dataset

In [6]:
#melakukan proses rename nama-nama kolom pada dataset
ColumnMapping = {"sepal_length" : "Sepal Length",
                "sepal_width" : "Sepal Width",
                "petal_length" : "Petal Length",
                "petal_width" : "Petal Width",
                "species" : "Species"}

DataIris.rename(columns = ColumnMapping, inplace = True)
DataIris

     Sepal Length  Sepal Width  Petal Length  Petal Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

Kode Script Untuk Dasbor Visualisasi Data Interaktif Dari Dataset Iris Dengan Menu Yang Di Tentukan

In [20]:
import warnings 

warnings.filterwarnings("ignore")

In [22]:
#terdapat beberapa library yang dipergunakan, yakni:
#library pandas untuk manipulasi data yang telah diload sebelumnya
#library matplotlib untuk visualisasi plot
import matplotlib.pyplot as plt

#library sklearn untuk k-means clustering
from sklearn.cluster import KMeans

#library ipywidgets, widgets untuk pembuatan elemen interaktif
import ipywidgets as widgets

#library ipywidgets, interactive output untuk widgets yang merespon perubahan input
from ipywidgets import interactive_output

#library ipython, display untuk menampilkan output
from IPython.display import display

#dengan menggunakan dataset "iris.csv" yang disimpan kedalam variabel DataIris, dilakukan langkah-langkah:
#melakukan penghapusan kolom "species" karena hanya menggunakan kolom numerik
DataNumeric = DataIris.drop(columns = ["Species"])


#define function konversi label hasil clustering menjadi spesies
def ConvertLabelsToSpecies(Labels):
    LabelMapping = {0 : "setosa", 1 : "versicolor", 2 : "virginica"}
    return [LabelMapping[Label] for Label in Labels]


#define function untuk scatter plot
def ScatterPlot(X, Y, Labels):
    SpeciesLabels = ConvertLabelsToSpecies(Labels)
    ColorMapping = {"setosa" : "red", "versicolor" : "blue", "virginica" : "olive"} #peta warna untuk cluster 0,1,2
    Colors = [ColorMapping[Species] for Species in SpeciesLabels] #menggunakan peta warna untuk setiap label cluster
    
    plt.scatter(X, Y, c = Colors) #pembuatan scatter plot k-means clusterring dengan sumbu x,y
    plt.xlabel(f"{X.name} (Cm)", fontsize = 14, fontname = "Times New Roman") #label sumbu x
    plt.ylabel(f"{Y.name} (Cm)", fontsize = 14, fontname = "Times New Roman") #label sumbu y
    plt.title("Scatter Plot Pengelompokkan Dataset Iris Dengan K-Means", fontsize = 16, 
              fontname = "Times New Roman") #label sumbu visualisasi
    
    #penambahan marker warna untuk visualisasi
    LegendMarkers = [plt.Line2D([0], [0], marker = "o", color = "w", markerfacecolor = ColorMapping[Species],
                                markersize = 10) for Species in ColorMapping.keys()]
    legend = plt.legend(LegendMarkers, ColorMapping.keys(), loc = "upper left", bbox_to_anchor = (1, 1), 
                        title = "Species", title_fontsize = 10, fontsize = 10)
    for text in legend.get_texts():
        text.set_fontname("Times New Roman")
    
    plt.show()
    
    
#define function untuk k-means clustering 
def KMeansClustering(Data, NClustering):
    KMeansModel = KMeans(n_clusters = NClustering) #objek model k-means dengan jumlah clustering yang ditentukan
    KMeansModel.fit(Data) #pelatihan dan pengelompokkan data kejumlah clustering yang ditentukan
    return KMeansModel.labels_ #jumlah keanggotaan untuk label cluster setiap data 


#define function untuk pengubahan visualisasi sesuai inputan
def UpdateScatterPlot(VariabelX, VariabelY, NClustering):
    X = DataNumeric[VariabelX] #inisiasi variabel x
    Y = DataNumeric[VariabelY] #inisiasi variabel y
    Labels = KMeansClustering(DataNumeric, NClustering) #perhitungan label clustering berdasarkan k-means
    ScatterPlot(X, Y, Labels) #pemanggilan fungsi untuk visualisasi scatter plot
    
    
#pembuatan menu pada dasbor untuk dropdown
OptionX = ["Sepal Length", "Sepal Width", "Petal Length", "Petal Width"]
OptionY = OptionX

#dropdown untuk variabel x,y, dan jumlah clustering
DropdownX = widgets.Dropdown(options = OptionX, value = "Sepal Length", description = "Variabel X : ", 
                             style = {"description_width" : "120px"})
DropdownY = widgets.Dropdown(options = OptionY, value = "Sepal Width", description = "Variabel Y : ", 
                             style = {"description_width" : "120px"})
DropdownNClustering = widgets.Dropdown(options = list(range(1, 4)), value = 3, description = "Jumlah Kelas Iris : ", 
                                       style = {"description_width" : "120px"})


#pembuatan output interaktif
Output = interactive_output(UpdateScatterPlot, {"VariabelX": DropdownX, "VariabelY": DropdownY, 
                                                "NClustering": DropdownNClustering})

#mengatur tata letak dashboard visualisasi
DashboardLayout = widgets.VBox([
    widgets.HTML("<h1 style='text-align:center;font-family:Times New Roman;'>Dasbor Visualisasi Interaktif Dataset Iris</h1>"),
    widgets.VBox([DropdownX, DropdownY, DropdownNClustering], layout = widgets.Layout(align_items = "center")),
    Output], layout = widgets.Layout(align_items = "center"))


#menampilkan output dashboard visualisasi iris
display(DashboardLayout)

VBox(children=(HTML(value="<h1 style='text-align:center;font-family:Times New Roman;'>Dasbor Visualisasi Inter…